# This is the docker-compose file to run Medplum's required background services
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'

volumes:
  postgres_data:
    external: true
    name: adc449535064eb71aada14aa7dbf901704e24fadafda9aeb9e22f5f00e2c96cd
